version: 2.1

orbs:
  win: circleci/windows@5.0

workflows:
  build-and-unittest:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    executor:
      name: win/default
      version: edge
    steps:
      - checkout
      - run:
         command: ls
      - run:
          name: Restore project dependencies and tools
          command: dotnet restore AnimalsApi.sln
      - run:
          name: Build project 
          command: dotnet build AnimalsApi.sln
      - run:
          name: "Running tests"
          command: |
            mkdir test-results
            dotnet test ./AnimalsApi.Tests --logger:trx
            ls
      - store_test_results:
          path: ./AnimalsApi.Tests/TestResults
      - store_artifacts:
          path: ./AnimalsApi.Tests/TestResults
  